### ISSUE TITLE
Is this game playable?

### ISSUE THREAD

**Issue by jdwilsonjr** [mscrnt/TextAdventure#1]
Hello,

This looks really cool. Definitely starred. Cloned and ran with no issues.

As no discussion am posting an issue to inquire whether game is playable. I have perused the docs and did not find (possibly overlooked) instructions on how to play.

Please advise if then where one might find instructions.

Again, apologies in advance if overlooked.

**Comment by mscrnt** [comment]
Hi! Thanks for the interest and star!

This game is in very early alpha. The framework is basically there, but quests and commands have not fully been implemented yet. I'll need to update my readme doc with that info.

My current focus is to get the worlds json completely fleshed out. Those files will provide the story and populate the worlds. 

You can disable ai_assist in world_builder.py if you don't have an openai api key. Typing help into the console should get you some basic commands to move and take items.

I should have a demo available in the next week or two

Feel free to add new quests if you'd like. That section should be safe for a bit now.

**Comment by jdwilsonjr** [comment]
that makes good sense.

i do have an openai account, however will disable ai_assist in world_builder.py as you suggest and bang around.

let me know if there is anything i can test for you. to be clear i am not a gamer, however, this caught my attention and will keep watch.

thank you for responding. might suggest discussions enabled. guessing there will be a lot of them ;-)
